#!/bin/sh


readonly DIR="/opt/minecraft-launcher"
readonly CHDIR="${HOME}/.minecraft"

if [ "${LD_LIBRARY_PATH+set}" = "set" ] ; then
	export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${DIR}"
else
	export LD_LIBRARY_PATH="${DIR}"
fi

test ! -d "${CHDIR}" && mkdir -p "${CHDIR}"
cd "${CHDIR}" && exec "${DIR}/minecraft-launcher" "$@"
