name: Bug report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees: ["beatussum"]

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!

  - type: input
    id: contact
    attributes:
      label: Contact details
      description: How can we get in touch with you if we need more info?
      placeholder: e.g. email@example.com

  - type: textarea
    id: what-happened

    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"

    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output

      description: |
        Please copy and paste any relevant log output.
        This will be automatically formatted into code, so no need for backticks.

      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Terms

      description: |
        Please check all the boxes that apply:

      options:
        - label: I agree to follow [this project's code of conduct](https://github.com/beatussum/beatussum-overlay/blob/main/CODE_OF_CONDUCT.md).
          required: true
        - label: I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
          required: true
        - label: This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
          required: true
