name: Run pkgcheck
on: [pull_request, push]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Run pkgcheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Run pkgcheck
        uses: pkgcore/pkgcheck-action@v1
